### ISSUE TITLE
Add method for on the window to award 100% points on all modules

### ISSUE THREAD

**Issue by theseanzo** [cdig/cd-launcher#2]
Because we have to test whether SCORM registers completion of the acid unit, it would be very helpful if there was a call on the window to just award all points. At least for debugging.

**Comment by ivanreese** [comment]
Or you could make a small test module. Or just use the small test module in the cd-launcher project repo (in the content folder)

**Comment by theseanzo** [comment]
Yeah, I used the small test module. Let's leave this for later.

**Comment by ivanreese** [comment]
The project is deprecated, so this is unnecessary.
