### ISSUE TITLE
Currently 100% on Trican doesn't register with SCORM as complete

### ISSUE THREAD

**Issue by theseanzo** [cdig/cd-launcher#3]
This may just be because of an issue in the content.json. I'll investigate.

**Comment by ivanreese** [comment]
I didn't test this feature when rewriting the SCORM code, so it might be my fault. If you don't conclusively find the cause right away, I can slay this one.

**Comment by theseanzo** [comment]
I will look into this in a bit and run a test. Should be okay, though.

**Comment by theseanzo** [comment]
This is fixed. It wasn't actually the content.json. There wasn't any way in the system to actually call the "Backend.complete()" so nothing was ever happening when we got 100%. It's tested in SCORM now, though.

**Comment by ivanreese** [comment]
:thumbsup:
